//! `forge.lock` — the generated, fully-resolved environment. It is what
//! `forge env sync` writes and `forge reproduce` replays. The offline runtime
//! bundle shipped in the installer is one concrete materialization of this file.
//!
//! Crate resolution is **not** duplicated here: the lock references `Cargo.lock`
//! by hash, keeping Cargo the source of truth for the crate graph. The reserved
//! `[native]`/`[gpu]`/`[python]` tables mirror the manifest and stay empty until
//! those providers ship.

use super::manifest::Manifest;
use serde::{Deserialize, Serialize};

/// Lock schema version, independent of the manifest schema.
pub const LOCK_SCHEMA: u32 = 1;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Lock {
    pub schema: u32,
    pub generated_at: String,
    pub forge_version: String,
    #[serde(default)]
    pub environment: LockEnvironment,
    #[serde(default)]
    pub cargo: LockCargo,
    /// One entry per provider that contributed to the environment — the unit of
    /// reproduction. Serialized as `[[provider]]` tables.
    #[serde(default, rename = "provider")]
    pub providers: Vec<LockEntry>,
    // Reserved, empty until the matching manifest sections ship.
    #[serde(default, skip_serializing_if = "toml::Table::is_empty")]
    pub native: toml::Table,
    #[serde(default, skip_serializing_if = "toml::Table::is_empty")]
    pub gpu: toml::Table,
    #[serde(default, skip_serializing_if = "toml::Table::is_empty")]
    pub python: toml::Table,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default)]
pub struct LockEnvironment {
    pub profile: Option<String>,
    pub channel: String,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default)]
pub struct LockCargo {
    /// SHA-256 of the project's `Cargo.lock`, tying reproduction to the exact
    /// crate graph. Empty when the project has no lockfile yet.
    pub lockfile_sha256: String,
}

/// What one provider materialized, recorded for reproduction.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LockEntry {
    /// Provider id (matches [`EnvironmentProvider::id`](super::provider::EnvironmentProvider::id)).
    pub id: String,
    /// Provider kind (e.g. `"offline-bundle"`).
    pub kind: String,
    /// Human-readable version (e.g. the toolchain version string).
    pub version: String,
    /// Integrity hash of what was materialized.
    pub sha256: String,
    /// Provider-specific extra fields (paths, secondary hashes, …).
    #[serde(default, skip_serializing_if = "toml::Table::is_empty")]
    pub extra: toml::Table,
}

impl Lock {
    /// Build a lock from a manifest and the providers' materialized entries.
    pub fn new(manifest: &Manifest, providers: Vec<LockEntry>, forge_version: &str) -> Lock {
        Lock {
            schema: LOCK_SCHEMA,
            generated_at: now_rfc3339(),
            forge_version: forge_version.to_owned(),
            environment: LockEnvironment {
                profile: manifest.environment.profile.clone(),
                channel: manifest.channel().to_owned(),
            },
            cargo: LockCargo::default(),
            providers,
            native: toml::Table::new(),
            gpu: toml::Table::new(),
            python: toml::Table::new(),
        }
    }

    /// Serialize to the `forge.lock` on-disk form.
    pub fn to_toml(&self) -> Result<String, String> {
        let body = toml::to_string_pretty(self).map_err(|error| error.to_string())?;
        Ok(format!("# forge.lock — generated by Forge ML; do not edit.\n{body}"))
    }

    pub fn from_toml(text: &str) -> Result<Lock, String> {
        toml::from_str::<Lock>(text).map_err(|error| error.to_string())
    }
}

/// SHA-256 of `bytes`, lowercase hex — the hashing used across the lock.
pub fn sha256_hex(bytes: &[u8]) -> String {
    use sha2::{Digest, Sha256};
    let digest = Sha256::digest(bytes);
    let mut hex = String::with_capacity(digest.len() * 2);
    for byte in digest {
        hex.push_str(&format!("{byte:02x}"));
    }
    hex
}

/// An RFC-3339 UTC timestamp for the generated-at field.
fn now_rfc3339() -> String {
    chrono::Utc::now().format("%Y-%m-%dT%H:%M:%SZ").to_string()
}
