[package]
name = "forge_ide"
version = "0.1.5"
edition = "2021"

[dependencies]
eframe = { version = "=0.36.0", features = ["persistence"] }
egui = "=0.36.0"
egui_plot = "=0.37.0"
egui_code_editor = "=0.3.8"
egui_phosphor_icons = { version = "=0.5.0", default-features = false }
evcxr = "0.18"
serde = { version = "1.0", features = ["derive"] }
rfd = "0.17.2"
serde_json = "1.0"
url = "2.5"
