#!/usr/bin/env bash
# Assemble the self-contained offline Rust runtime that Forge ML ships so that
# notebook `:dep` cells and generated projects using Millwright and Burn compile
# and run with NO network and NO user-installed toolchain.
#
# Output layout (consumed by src/offline.rs):
#
#   packaging/forge-runtime/
#     bin/            cargo, rustc, rustdoc, ...   (the pinned toolchain)
#     lib/            rustlib sysroot for the above
#     cargo-home/
#       config.toml   offline + crates.io -> vendored-sources
#       vendor/       every crate in the workspace lockfile, pre-downloaded
#     VERSION         `rustc --version`, shown in the app
#
# Run on each release platform (Linux/macOS); see build-offline-bundle.ps1 for
# Windows. Requires rustup + the pinned toolchain (rust-toolchain.toml) and one
# network-enabled run to populate the vendor directory.
set -euo pipefail

repo_root="$(cd "$(dirname "$0")/.." && pwd)"
out="$repo_root/packaging/forge-runtime"
sysroot="$(rustc --print sysroot)"

echo ">> Toolchain sysroot: $sysroot"
rm -rf "$out"
mkdir -p "$out/cargo-home"

# 1. Stage the toolchain (bin + lib/rustlib) so rustc finds its sysroot relative
#    to bin/, exactly as in a normal install.
echo ">> Staging toolchain into $out"
cp -a "$sysroot/bin" "$out/bin"
cp -a "$sysroot/lib" "$out/lib"

# 2. Vendor the entire workspace dependency closure (millwright + burn + all
#    transitive crates) at the exact locked versions the app was built against.
echo ">> Vendoring dependencies (this needs network once)"
cargo vendor --locked --manifest-path "$repo_root/Cargo.toml" "$out/cargo-home/vendor" \
  > "$out/cargo-home/vendor-config.toml"

# 3. Write the CARGO_HOME config: force offline and replace crates.io with the
#    vendored sources. `src/offline.rs` sets CARGO_HOME to this directory.
cat > "$out/cargo-home/config.toml" <<'EOF'
# Generated by packaging/build-offline-bundle.sh — do not edit by hand.
[net]
offline = true

[source.crates-io]
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"
EOF
# `cargo vendor` prints the exact [source] stanza it wants; keep it for reference
# but our hand-written block above uses a path relative to CARGO_HOME.

# 4. Record the toolchain version for display in the app.
rustc --version > "$out/VERSION"

echo ">> Done. Offline runtime staged at $out"
du -sh "$out" 2>/dev/null || true
