# Assemble the self-contained offline Rust runtime that Forge ML ships so that
# notebook `:dep` cells and generated projects using Millwright and Burn compile
# and run with NO network and NO user-installed toolchain. Windows counterpart of
# build-offline-bundle.sh; see that file for the output layout consumed by
# src/offline.rs.
#
# Run on a Windows release host with rustup + the pinned toolchain
# (rust-toolchain.toml) and one network-enabled run to populate the vendor dir.
$ErrorActionPreference = "Stop"

$repoRoot = Split-Path -Parent $PSScriptRoot
$out = Join-Path $repoRoot "packaging\forge-runtime"
$sysroot = (& rustc --print sysroot).Trim()

Write-Host ">> Toolchain sysroot: $sysroot"
if (Test-Path $out) { Remove-Item -Recurse -Force $out }
New-Item -ItemType Directory -Force -Path (Join-Path $out "cargo-home") | Out-Null

# 1. Stage the toolchain (bin + lib) so rustc finds its sysroot next to bin/.
Write-Host ">> Staging toolchain into $out"
Copy-Item -Recurse -Force (Join-Path $sysroot "bin") (Join-Path $out "bin")
Copy-Item -Recurse -Force (Join-Path $sysroot "lib") (Join-Path $out "lib")

# 2. Vendor the whole workspace dependency closure at locked versions.
Write-Host ">> Vendoring dependencies (this needs network once)"
$vendorDir = Join-Path $out "cargo-home\vendor"
& cargo vendor --locked --manifest-path (Join-Path $repoRoot "Cargo.toml") $vendorDir |
  Out-File -Encoding utf8 (Join-Path $out "cargo-home\vendor-config.toml")

# 3. Write the CARGO_HOME config: offline + crates.io -> vendored sources.
@'
# Generated by packaging/build-offline-bundle.ps1 - do not edit by hand.
[net]
offline = true

[source.crates-io]
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"
'@ | Out-File -Encoding utf8 (Join-Path $out "cargo-home\config.toml")

# 4. Record the toolchain version for display in the app.
(& rustc --version) | Out-File -Encoding ascii (Join-Path $out "VERSION")

Write-Host ">> Done. Offline runtime staged at $out"
