#!/usr/bin/env bash
# Generate Forge's starter native-prerequisite catalog by fetching each pinned
# prebuilt and computing its SHA-256. Writes the catalog TOML to stdout; the
# `native-catalog` GitHub workflow redirects it to packaging/native-catalog.toml
# and commits any change.
#
# It does not run the tools — it only downloads and hashes the archives, so it
# runs on any single Linux runner and pins every platform. A wrong URL fails the
# job (nothing is committed) rather than shipping a bad catalog.
#
# The catalog rows below are the source of truth. Bump a version here and the
# next run repins it. Format per row:
#   name|kind|version|target|archive|bin_dir|url
set -euo pipefail

CMAKE=3.30.5
PROTOC=28.3
NINJA=1.12.1

rows() {
  # ── ninja: single binary at the archive root (bin_dir ".") ──────────────────
  echo "ninja|tool|${NINJA}|x86_64-windows|zip|.|https://github.com/ninja-build/ninja/releases/download/v${NINJA}/ninja-win.zip"
  echo "ninja|tool|${NINJA}|x86_64-linux|zip|.|https://github.com/ninja-build/ninja/releases/download/v${NINJA}/ninja-linux.zip"
  echo "ninja|tool|${NINJA}|aarch64-linux|zip|.|https://github.com/ninja-build/ninja/releases/download/v${NINJA}/ninja-linux-aarch64.zip"
  echo "ninja|tool|${NINJA}|aarch64-macos|zip|.|https://github.com/ninja-build/ninja/releases/download/v${NINJA}/ninja-mac.zip"
  echo "ninja|tool|${NINJA}|x86_64-macos|zip|.|https://github.com/ninja-build/ninja/releases/download/v${NINJA}/ninja-mac.zip"

  # ── protoc: bin/protoc inside the archive (bin_dir "bin") ────────────────────
  echo "protoc|tool|${PROTOC}|x86_64-windows|zip|bin|https://github.com/protocolbuffers/protobuf/releases/download/v${PROTOC}/protoc-${PROTOC}-win64.zip"
  echo "protoc|tool|${PROTOC}|x86_64-linux|zip|bin|https://github.com/protocolbuffers/protobuf/releases/download/v${PROTOC}/protoc-${PROTOC}-linux-x86_64.zip"
  echo "protoc|tool|${PROTOC}|aarch64-linux|zip|bin|https://github.com/protocolbuffers/protobuf/releases/download/v${PROTOC}/protoc-${PROTOC}-linux-aarch_64.zip"
  echo "protoc|tool|${PROTOC}|aarch64-macos|zip|bin|https://github.com/protocolbuffers/protobuf/releases/download/v${PROTOC}/protoc-${PROTOC}-osx-aarch_64.zip"
  echo "protoc|tool|${PROTOC}|x86_64-macos|zip|bin|https://github.com/protocolbuffers/protobuf/releases/download/v${PROTOC}/protoc-${PROTOC}-osx-x86_64.zip"

  # ── cmake: extracts to a versioned dir; bin_dir includes it (per target) ─────
  echo "cmake|tool|${CMAKE}|x86_64-windows|zip|cmake-${CMAKE}-windows-x86_64/bin|https://github.com/Kitware/CMake/releases/download/v${CMAKE}/cmake-${CMAKE}-windows-x86_64.zip"
  echo "cmake|tool|${CMAKE}|x86_64-linux|tar-gz|cmake-${CMAKE}-linux-x86_64/bin|https://github.com/Kitware/CMake/releases/download/v${CMAKE}/cmake-${CMAKE}-linux-x86_64.tar.gz"
  echo "cmake|tool|${CMAKE}|aarch64-linux|tar-gz|cmake-${CMAKE}-linux-aarch64/bin|https://github.com/Kitware/CMake/releases/download/v${CMAKE}/cmake-${CMAKE}-linux-aarch64.tar.gz"
  echo "cmake|tool|${CMAKE}|aarch64-macos|tar-gz|cmake-${CMAKE}-macos-universal/CMake.app/Contents/bin|https://github.com/Kitware/CMake/releases/download/v${CMAKE}/cmake-${CMAKE}-macos-universal.tar.gz"
  echo "cmake|tool|${CMAKE}|x86_64-macos|tar-gz|cmake-${CMAKE}-macos-universal/CMake.app/Contents/bin|https://github.com/Kitware/CMake/releases/download/v${CMAKE}/cmake-${CMAKE}-macos-universal.tar.gz"
}

tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT

sha_of() {
  local url="$1" file="$tmp/dl"
  # Fail loudly on a bad URL so the job stops instead of pinning a 404 body.
  curl -fsSL --retry 3 --retry-delay 2 -o "$file" "$url"
  sha256sum "$file" | cut -d' ' -f1
}

echo "# Forge starter native-prerequisite catalog."
echo "#"
echo "# GENERATED by packaging/generate-native-catalog.sh — do not edit by hand."
echo "# Every entry is verified by SHA-256 before use. Regenerated by the"
echo "# native-catalog workflow. cmake ${CMAKE} · protoc ${PROTOC} · ninja ${NINJA}."
echo ""

# Emit one [[artifact]] per tool, grouping its target rows.
last=""
while IFS='|' read -r name kind version target archive bin_dir url; do
  [ -z "${name:-}" ] && continue
  if [ "$name" != "$last" ]; then
    echo ""
    echo "[[artifact]]"
    echo "name = \"$name\""
    echo "kind = \"$kind\""
    echo "version = \"$version\""
    last="$name"
  fi
  sha="$(sha_of "$url")"
  echo ""
  echo "[artifact.targets.$target]"
  echo "url = \"$url\""
  echo "sha256 = \"$sha\""
  echo "archive = \"$archive\""
  echo "bin_dir = \"$bin_dir\""
done < <(rows)
